### ISSUE TITLE
Some suggestions for improvement mod to Pressure Pipes. .

### ISSUE THREAD

**Issue by SilenceDuan** [bdew-minecraft/pressure#1]
Pressure Pipes mod is very powerful, but do not know JAVA like me who want to make this MOD has a better balance is not easy, it cost too low, and it can be a huge moment pumped liquid container, I hope you make this mod, there is a list of more configuration options, you can change the synthetic materials needed, as well as extraction speed, so your mod before anyone dared to control, otherwise it is too fierce, no balance that we can not join this super Pressure Pipes mod ...
My English is not very good, I hope you can understand ...

**Comment by bdew** [comment]
This is not a bug and balance is better discussed on the [forums](http://www.minecraftforum.net/topic/2727722-) where other users can participate.
