### ISSUE TITLE
[1.10.2] Extreme Reactors crash

### ISSUE THREAD

**Issue by YOYOK9** [bdew-minecraft/pressure#101]
Have pressure pipes pushing and pulling water in and out of Extreme reactor and turbines.

https://pastebin.com/ZWhzkHHS

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
