### ISSUE TITLE
[1.7.10] Fluid dupe with tank controller

### ISSUE THREAD

**Issue by vaIgarashi** [bdew-minecraft/pressure#103]
<del>Bugs found by my server staff. https://image.prntscr.com/image/6Flnd82XT1Opnw_A_APRbw.jpeg
Both, left and right tank blocks keeps getting liquid. <del>

When tank controller have low fluid it's starting to dupe. https://prnt.sc/gel3ru

**Comment by bdew** [comment]
How did you manage to separate them like that?

It's probably not a real dupe, just showing the same content on both sides since they still think they are part of the same tank structure... if you drain them do you actually get twice the amount?

**Comment by ensirius** [comment]
It's hard to understand what exactly dupe, but if place blocks like that it's start dupe luquid. https://image.prntscr.com/image/sQkbMyASQHyoV8znExV6hg.jpeg

**Comment by vaIgarashi** [comment]
We a bit investigated into a problem. It's accur when fluid transfers is too slow. For example we use Galaticraft oil processor. When tank controller left around ~9MB it's start to dupe. Galacticraft oil processor must be full to not allow transfer all left fluid from tank controller.

**Comment by ensirius** [comment]
This line looks wrong for me https://github.com/bdew/pressure/blob/mc1710/src/net/bdew/pressure/pressurenet/PressureConnection.scala#L43. It's return negative int
