### ISSUE TITLE
[1.12] Suggestion - Add an output that'll fill every air block inside of a contained space.

### ISSUE THREAD

**Issue by llloyd4** [bdew-minecraft/pressure#104]
Eh, how do I best describe this. Just like the old Buildcraft 'Flood Gate', which could create a lake with an infinite water source, pump, and a flood gate hanging over the side. Though I am thinking of the more practical application of filling and, maybe, draining Extreme Reactors. Though making artificial lakes is a pretty neat idea too. :D Or, as a friend of mine did one time, put up walls of glass and back fill behind them with lava or other liquids for some pretty cool effects for the walls. :D

**Comment by bdew** [comment]
Sorry i'm not going to be accepting feature requests in the issue tracker, as their inflow far outpaces my ability to implement them.

I'm going to figure out a better platform to manage feature requests soon (tm).
