### ISSUE TITLE
Possible localization issue with NEI creative search?

### ISSUE THREAD

**Issue by BevoLJ** [bdew-minecraft/pressure#2]
I ran into something like this with Railcraft and the names for the RC Forestry Backpacks and Covert just fixed it, but seems someone is having a crash when trying to search in creative

Here is the crash log: http://pastebin.com/ng6vpjQ4
Here is the issue on my git: https://github.com/BevoTechPack/BevoTechPack/issues/270#issuecomment-52528227

Edit: I'm guessing it is localization and pressure pipes cause honestly I don't know what 99% of that in the log means.  :P

**Comment by bdew** [comment]
Looks like a broken installation, fixed by the user re installing.
