### ISSUE TITLE
No config?

### ISSUE THREAD

**Issue by slawr34** [bdew-minecraft/pressure#20]
Is this mod supposed to generate a config? On Bdew's website is says that you can change the efficiency of your generator but there is no config to do so.

**Comment by bdew** [comment]
I'm assuming this is for Advanced Generators and you just posted this on the wrong mod...

You should have a folder <minecraft>/config/AdvGenerators - in there you can write your own configuration sinppets

For eample, create a file "whatever.cfg"

```
cfg Machines {
    cfg TurbineController {
        MJPerTickPerTurbine = 10    
        FuelConsumptionMultiplier = 0.9
        cfg FuelValues {
            fluidname = 80  // this can add or override the value of fuels
        }
    }
}
```

And this will be merged with the internal config and can override the values there. Look [here](https://github.com/bdew/generators/tree/mc-1.7.10/resources/assets/advgenerators/config) for examples of what can be changed.

You can also extract the internal configs from the jar into <minecraft>/config/AdvGenerators/overrides and edit them there, but you will need to manually update that when the mod udpates.

I'm currently writing up some proper documentation for this system (which is the same for all my mods).

**Comment by slawr34** [comment]
Haha oops, yes this was meant to go to Advanced Generators.

Thanks for that suggestion, it's somewhat cooler making your own config than editing a preexisting one. Correct me if I'm wrong: A fuel consumption value of 1.0 means that the amount of fuel used is equal to that used in regular generators and a higher value is more inefficient. 

As an aside, did you have any plans adding lava to fluids usable in the generator?

Again, thanks!

**Comment by bdew** [comment]
Lava will be useable in some other form, probably to produce steam which can then be used to generate power. This should be in the next few versions.

**Comment by slawr34** [comment]
Anyway, obviously don't want to start a discussion here but looking forward to it. Keep up the good work!
