### ISSUE TITLE
Make Tanks Larger

### ISSUE THREAD

**Issue by Fuhrmaaj** [bdew-minecraft/pressure#31]
I would like to know if it would be possible to change the maximum number of blocks allowed in Pressure Pipes tanks? Currently a player may have up to 50 Storage Blocks as well as the other blocks required for manipulating fluids, for a maximum total of 76 blocks. I'd like to be able to make larger tanks, like 5x5 at the base and 6-8 blocks tall for example.

Would it be possible to add a config option to allow for larger tanks? Right now I have to hollow out the tank and try to figure out what types of blocks I can plug into the wall to make it look like they're part of the tank so I can make them look bigger. To clarify, I want larger tanks purely for aesthetic reasons.

**Comment by bdew** [comment]
Make a file <minecraft>/config/PressurePipes/<whatever>.cfg and put in it:

```
  cfg Machines {
      cfg TankController {
          cfg Modules {
              TankBlock = 100 // Maximum number of tank blocks here
          }
      }
  }
```

I might increase the default for next version.

**Comment by Fuhrmaaj** [comment]
Thanks a lot for this! Is this documented somewhere? I saw a similar type of config file in the Mod Spotlight that MysteryDump did, might be interesting to know if there's anything else I can tinker with.

**Comment by Fuhrmaaj** [comment]
Sorry to harass you, I made a custom file to try to replicate the default settings, I just wanted to make sure that this looks correct:

cfg Machines {
     cfg TankController {
          cfg Modules {

```
           TankBlock = 50 // Maximum number of tank blocks here

           cfg TankBlock {
                Capacity = 32000 // Capacity of tank blocks in mB here
           }
      }
 }
```

}

**Comment by bdew** [comment]
There's documentation of the format [here](http://bdew.net/bacon/) and specifics to Pressure Pipes [here](http://bdew.net/pressure/configuration/). Also you can look at the [default configs](https://github.com/bdew/pressure/tree/mc1710/resources/assets/pressure/config).

What you wrote should look like 

```
    cfg Modules {
        cfg TankBlock {
            Capacity = 32000
        }
    }

    cfg Machines {
      cfg TankController {
          cfg Modules {
              TankBlock = 100
          }
      }
    }
```

Modules settings are separate from machines sections, in case in the future i add other multiblock structures that can share modules with the tank.

**Comment by Fuhrmaaj** [comment]
Hey, thanks a lot for your help bdew! Sorry, I was looking at your website and I didn't look hard enough to find this information. I really appreciate the work you've put into this mod, as well as NEI Addons and Gendustry which I also use. Thanks so much for helping me here!
