### ISSUE TITLE
Fluid multiplication with hand pump

### ISSUE THREAD

**Issue by BakermanLP** [bdew-minecraft/pressure#33]
For example: If you habe a stack (64) drums in your inventory and click with the hand pump on a fluid, all 64 drums will be filled with 1000 mB of this liquid. I think, that is a bug, or?

**Comment by bdew** [comment]
Ugh yeah it is. That interface is really awkward to use with stackable items, i've done some special casing for that in tanks but missed the hand pump.

**Comment by bdew** [comment]
I've tried to figure out a foolproof algorithm that will work in all edge cases and never do something stupid - and failed >.>

This is a temporary fix to prevent duping for now, i'll leave this bug open until i figure out a full fix.

**Comment by bdew** [comment]
This took ~1.5 years but... hopefully is fixed now. The hand pump will auto-unstack stacked containers when filling them.
