### ISSUE TITLE
Any chance of a combination input/output block?

### ISSUE THREAD

**Issue by Tkdmaster** [bdew-minecraft/pressure#35]
Hey there! Apologies if this is not in the correct place, but I wasn't sure where else to post this.

My question is, is there any chance a combination block could be implemented in? Alot of machine factories in GregTech need both inputs and outputs from 1 machine, and its rather difficult to try and free up more sides of them with limited space/other automation of item piping around with this. The ability to both output and input from 1 block would be immensely valuable I would think.

**Comment by bdew** [comment]
I'll consider this for a future version, it should be pretty easy to code but i'm not sure how to make it non-awkward to use (it would need 2 filter slots, so either a GUI to set them or some form of multiple clickable areas on the block, and maybe separate redstone control? etc...)

**Comment by Tkdmaster** [comment]
Well...I think a gui could work nicely, but not sure if you're wanting to implement any more of those, considering most things in the mod don't have/require one. If not, then I'd say maybe use the wrenching functionality work independently on the faces to reconfigure the block sides? So say...if you use a wrench on the top, you can toggle it form input to output, etc.

**Comment by hron84** [comment]
About the GUI, consider an interface like how EnderIO Item Conduits works when you configure them to In/Out mode, there is a little arrow where you can switch between the two different GUI (altough they aren't **so** different).

**Comment by bdew** [comment]
Took me a bit less than a year (sorry... :P) but implemented in this build http://minecraft.curseforge.com/projects/pressure-pipes/files/2280379
