### ISSUE TITLE
Upgradeable Handpump

### ISSUE THREAD

**Issue by Unrepentant-Atheist** [bdew-minecraft/pressure#38]
Would be nice to have a RF charged handpump that can pump like 3x3x3 or 5x5x5 area for clearing large lakes for fluids.

Should be mid/late game and bit expensive to craft.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
