### ISSUE TITLE
Some suggestions.

### ISSUE THREAD

**Issue by anishin** [bdew-minecraft/pressure#40]
Firstly, thank you for your work!
Secondly, I have some suggestions for this mod.
1) Block with configurable input/output (It is not always convenient to replace the entire block.)
2) Block with input AND output (as it made with fluid conduits in EnderIO, for example).
3) (If it is possible). Add channels for transfer liquids (again, as it made in EIO).
4) Microblock variants of all buses in this mod (like interfaces from AE2; sometimes buses from this mod is bulky and clumsy).
5) Tiers of modular tank. (Now it's capacity is too small compared with tanks from other mods).
6) And finally. Make recipe of canister harder (Now it's cheap as cheat!).

Thank you very much for your work!
P. S. Sorry for my English. I'm from Russia.

**Comment by bdew** [comment]
> 1) Block with configurable input/output (It is not always convenient to replace the entire block.)
> 2) Block with input AND output (as it made with fluid conduits in EnderIO, for example).

The router kinda covers that. It can have input and output sides configured and it can interact with both normal tank/machines/pipes and the pressure network. It can't do input + output at the same face from the same face for now which i would like to improve at some point.

> 3) (If it is possible). Add channels for transfer liquids (again, as it made in EIO).

You already have infinite "channels". You can configure what goes where using filters on input/output blocks.

> 4) Microblock variants of all buses in this mod (like interfaces from AE2; sometimes buses from this mod is bulky and clumsy).
> 5) Tiers of modular tank. (Now it's capacity is too small compared with tanks from other mods).

It's on my todo list.

> 6) And finally. Make recipe of canister harder (Now it's cheap as cheat!).

I disagree... It's more or less a glorified bigger bucket, i don't see why it should cost more. However you can always change it in the config :P

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
