### ISSUE TITLE
suggestion: Open Computers support

### ISSUE THREAD

**Issue by nightstalker6669** [bdew-minecraft/pressure#41]
just as the title says. I'm sure there are people out there that don't have computer craft on their servers, but they do have open computers. I would have tried to do it myself, but i know nothing of scala.

**Comment by bdew** [comment]
You can use a [controller](http://ocdoc.cil.li/block:adapter) from OC to connect to the tank data port.

**Comment by nightstalker6669** [comment]
thats strange, because i have OC ver 1.5.13 installed with your latest version from jenkins (1.2.1.108) and that block doesn't show up in NEI or the creative tab.

**Comment by bdew** [comment]
hmm i'll look into it

**Comment by CrazyCodeUK** [comment]
Using pressure pipes 1.2.3 and open computers 1.5.15 with forge 1492 the tank data port is not available with open computers installed (but not computercraft).

Enjoying the mod. Thanks :)

**Comment by hron84** [comment]
The tank data port needs CC networking cables according to the wiki, so I think it is uncraftable if no CC installed at all.
