### ISSUE TITLE
Filter for Mekanism Gas as Liquid

### ISSUE THREAD

**Issue by Skar78** [bdew-minecraft/pressure#42]
I want to configure filters for the High Pressure Router for Liquid Gases from Mekanism.

As I dont get them in a bucket I have a hard time to figure out how to set the filter.

**Comment by Skar78** [comment]
Ok, "configurator" on gas in/output seems to give a nice GUI for selecting. Only the router does not.

**Comment by bdew** [comment]
Hm i'll add a way to use a configurator to set filters on a router (i guess clicking a face will set a filter for that side?)

Until then you can use any kind of fluid container to set them, all gases have a fluid form (e.g. liquid hydrogen)

**Comment by Skar78** [comment]
It is not possible to convince a tank to fill a bucket with the liquid form. (..with the filler slot.)

**Comment by bdew** [comment]
Try a canister. Buckets need some mod to register a separate item for every fluid that they can hold, and i don't think mekanism does that for it's fluids.

**Comment by Skar78** [comment]
Canister is working to get the fluid inside and also allows to set filters on the router. Thanks.
