### ISSUE TITLE
NoClassDefFoundError: codechicken/multipart/MultiPartRegistry$IPartFactory2

### ISSUE THREAD

**Issue by Ganjalf-Amsterdoom** [bdew-minecraft/pressure#44]
Hello,

I tried the stable pressure mod and the latest jenkins version and it crashes with this:

http://pastebin.com/A7wt5M3D

**Comment by bdew** [comment]
Try updating ForgeMultiPart to a more modern version

**Comment by Ganjalf-Amsterdoom** [comment]
Thank you very much.
