### ISSUE TITLE
High Pressure Pump Not Working With Rotary Craft Pipes

### ISSUE THREAD

**Issue by RoloEdits** [bdew-minecraft/pressure#46]
When Trying To Hook p A Liquid Pipe To the Pump It Does Not Work.
![2015-07-18_10 47 35](https://cloud.githubusercontent.com/assets/12489689/8762886/a764bebe-2d3a-11e5-8826-58b63bf75593.png)

it looks like it does but its not just visual, there no water going through it.

![2015-07-18_10 47 47](https://cloud.githubusercontent.com/assets/12489689/8762888/bec64af0-2d3a-11e5-84a8-5d174460b0b0.png)

**Comment by bdew** [comment]
Those pipes are not "real" pipes (in any sense that forge and every other mod understands).

You can use RC pipes to input if you connect something from the top/bottom and output if you connect from the sides, but you can't push into them.

![example](http://i.imgur.com/tDKLeZp.png)

**Comment by RoloEdits** [comment]
OK Thank You I Think I Understand Now :)
