### ISSUE TITLE
Crash on server forge

### ISSUE THREAD

**Issue by Tander** [bdew-minecraft/pressure#58]
Exception in server tick loop:

Java Version: 1.8.0_66
Forge 11.15.0.1715

[crash-2016-01-24_07.19.15-server.txt](https://github.com/bdew/pressure/files/102158/crash-2016-01-24_07.19.15-server.txt)

**Comment by bdew** [comment]
Should be fixed in this build - http://minecraft.curseforge.com/projects/pressure-pipes/files/2277258
