### ISSUE TITLE
[Question] FakeTank

### ISSUE THREAD

**Issue by KidsDontPlay** [bdew-minecraft/pressure#63]
hi

`override def getTankInfo(from: EnumFacing) =
    if (isValidDirectionForFakeTank(from))
      Array(new FluidTankInfo(null, Int.MaxValue))
    else
      null`

why do you return null instead of an empty array?

**Comment by bdew** [comment]
No specific reason, AFAIR. Can change it if it causes problems, but there are other mods that do it - so you should expect getting a null from there and treating it correctly.
