### ISSUE TITLE
[Another Question] TileFluidOutput drain

### ISSUE THREAD

**Issue by KidsDontPlay** [bdew-minecraft/pressure#64]
me again,
I try to drain from tankfluid outlet, but canDrain() and drain() return 'null' respectively 'false'.
I guess the reason is that the outlet doesn't change its texture (the red arrows).
But why? Do I have to implement IFluidHandler ?

Filling the intake works fine.

I cannot read scala

**Comment by bdew** [comment]
Yes they currently only operate by pushing the fluid out, you can't drain from there. They also need the pipe/tank/whatever they are outputting to implement IFluidHandler so they can detect it and assign an output color to that face.

I'm planning to add a workaround similar to what i did [here](https://github.com/bdew/generators/issues/82#issuecomment-194840727) for RF. This is only for tanks, the pressure pipe system can only operate in push mode and this isn't going to change.

It would make everyone's life easier if mods allowed pushing into pipes and implemented the right interfaces on them. If BuildCraft and EnderIO (and TE back in 1.7.10) can do it, so can the rest.  

There is also  Tank Access Port that allows bi-directional (fill/drain) access to the tank, but it doesn't have some of the features provided by the outlets (RS control, flow rate monitoring, etc.)

**Comment by JCMais** [comment]
@bdew little off-topic, but do you know any mod that implements working normal pipes in 1.9?

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
