### ISSUE TITLE
[1.3.1.1] Sluice replaces itself with water

### ISSUE THREAD

**Issue by OhiraKyou** [bdew-minecraft/pressure#66]
Minecraft 1.9.4
Forge 1.9.4-12.17.0.1951
Pressure Pipes 1.3.1.1

Hook a sluice up to the output of a tank filled with some water. It will become a water source block.

**Comment by bdew** [comment]
heh, good one. will be fixed in next alpha.

**Comment by bdew** [comment]
Should be fixed with the latest build, sory for the long delay.
