### ISSUE TITLE
NEI not JEI for 1.9.4

### ISSUE THREAD

**Issue by MrAmericanMike** [bdew-minecraft/pressure#67]
I know the config says "B:"Add filled canisters to NEI"=false"
In 1.9.4 I believe we only have JEI, but even when I set false, all the canisters still showing, is there any way to hide them from showing on JEI?

Thanks.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
