### ISSUE TITLE
Server crash with 1.3.1.4

### ISSUE THREAD

**Issue by xannor** [bdew-minecraft/pressure#68]
I get the following crash when I upgrade to the latest pressure pipes and bdlib.

[Crash Report](https://gist.github.com/xannor/5f868822e5e7b29987c1fa5dd450b3e6)

Stepping back to 1.3.1.3 the problem goes away so it seems to be an issue with the new capabilities. The only issue with stepping back was that my multipart tank said it required one tank block, breaking and replacing one block fixed this but lost the contents of the tank. Otherwise stepping back seems to work fine.

edit: had to break and rebuild entire tank, would not recognize capacity until I did.

**Comment by bdew** [comment]
Should be fixed in this build: http://minecraft.curseforge.com/projects/pressure-pipes/files/2316343
