### ISSUE TITLE
Infinite water source block disappears

### ISSUE THREAD

**Issue by kalsmeer** [bdew-minecraft/pressure#70]
Hello,

I was using a dispenser to collect water from the infinite water source and the block just disappeared, in the inventory of the dispenser was a filled bucket. I assume this is not intended.

This happened in 1.3.1.10 for 1.10.2

**Comment by bdew** [comment]
Forge bug. Happens with any kind of tank with dispensers.

MinecraftForge/MinecraftForge#3165
