### ISSUE TITLE
EnderIO Ender Fluid Conduit not working at World Load

### ISSUE THREAD

**Issue by DiscipleOfUrza** [bdew-minecraft/pressure#72]
v.1.10.2

Whenever my single-player worled loads, the EnderIO Fluid Conduits I have connected to each of my three Tanks (input, from either Forestry Stills, EnderIO The Vats, or the Syngas Producer) do not transfer fluid. I need to break the conduit and replace it, after which it works as intended.

**Comment by DiscipleOfUrza** [comment]
Tank Fluid Intake is where the problem is occurring. *

**Comment by bdew** [comment]
I can't reproduce this. 

Are you on the latest versions of EnderIO and Pressure Pipes? Anything else special about your setup that might cause issues? Is this on a server or local? Chunkloading?

**Comment by DiscipleOfUrza** [comment]
Latest versions of both, local single player server, and I do have chunkloaders. However, while checking versions, I noticed I was quite behind on updates for Forge. Updating seems to have fixed the issue. Thank you, and might I add that you have some really, really great mods. Some of my very favorites!
