### ISSUE TITLE
Sluice Usage

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/pressure#73]
This may be a feature request or this may be a stupid user problem... :)

Trying to use PP to output a single bucket of a fluid at a time. Sluice seems obvious solution! Thing is, I want to drop _one_ bucket and not drop the next bucket until the first bucket of fluid is gone, aka there is an air block in front of sluice. It seems it just rockets through the fluid storage and repeatedly places the fluids down. I blew through a drum of lava in no time.

Use case? Trying to make an obsidian gen and only want to place a single bucket of lava into the stream of water, let my EU miner break the resulting obsidian block, and then place another bucket of lava. Repeat.

It works... sort of. Out of 256 buckets I got 18 obsidian blocks. The sluice just keeps dumping buckets rapid fire and if it happens to turn to obsidian, the mechanical miner breaks it and grabs it but seems to be dumping buckets faster than obsidian forms so it burns through the tank with, as you can see, very low efficiency. :)

So if I am using the sluice properly... my request would be a way to set it to only drop a single bucket and wait for that fluid to be gone from in front of it before dropping another [either as default behavior or one we can set].

Or I'm doing something stupid....

Or it's a bug with lava not detecting right if it is supposed to only work as I hoped for already.

MC 1.10.2
PP 1.3.1.11

Thanks :)

**Comment by bdew** [comment]
Sounds like a bug, i'll look into it.

**Comment by Utildayael** [comment]
Thanks bdew! I was afraid it was stupid user error. I read the wiki and it _seemed_ like it wasn't supposed to place a bucket of fluid until previous one was gone. :)

**Comment by bdew** [comment]
Should be fixed in this build: https://minecraft.curseforge.com/projects/pressure-pipes/files/2326960

**Comment by Utildayael** [comment]
Thank you sir!
