### ISSUE TITLE
Tanks Causing Stuttering

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/pressure#74]
This may be the same issue chloe was seeing but figured I'd report nonetheless.

When I make a tank [5x5x5 in this case] and it is inputting or outputting fluid I get major stuttering.

My FPS is nearly constant but the game literally stutters as I walk around anywhere near the tank. I broke the input and output lines going in/out of it and the stuttering immediately went away. I was using the high pressure pipes in/out.

Basic setup. 5x5x5 tank receiving brine from Mekanism evap towers [4 of them]. The tank then outputs to my separators for further processing. Having either output or input connecting brings the stutter as I tested both to see if it was only output or only input... no difference. Note that my input is a small network of high pressure pipes from the 4 towers whereas my output is only a single pipe from tank to electro separator. Using HP pumps to pull from the towers into the HP pipes into the tank for input  and using HP outlet to convert from HP to regular pipe to feed the electro sep on the output line. Nothing too fancy. 

I'm feeding my 4 towers water from a PP infinite water block with pump > input > pipe > outlet setup and that causes no stuttering nor do the other small setups I have with PP around my base so it seems to be tank-related.

Please let me know if there is anything else I can provide. This is on a server if that helps.

Thanks!

Minecraft 1.10.2
Pressure Pipes 1.3.1.11
Forge 2065

**Comment by Utildayael** [comment]
For kicks tried a couple more scenarios:
1. Hooked non-pressure pipe for input into tank. Still stuttered.
2. Dumped HP line into a EU drum then used normal pipe to input into tank. Still stuttered.
3. Used just a normal line from an EU drum into the tank. Still stuttered.

So the commonality here seems to be the tank since I removed the entire pipe network [#3] and it still stuttered. :(

**Comment by bdew** [comment]
This is currently an issue with my tile entities server->client sync code that causes more chunk rendering updates than needed. If there is anything with a heavy/complicated model in the same 16x16x16 cube with the controller - it might cause some stutter.

I'll be reworking how that system works to allow me more control over when rendering updates happen soon(tm).

As a temporary solution you can remove all tank indicator blocks (this will prevent a rendering update from being sent) or place the controller in a position which doesn't include any complicated blocks in the same 16x16x16 cube.

**Comment by Utildayael** [comment]
I'll give that a try. I did have two tank indicators and I need to confirm that my tank was not in the same chunk as the four evap towers which are big 4x4x18 multi blocks. I know those four were same chunk but thought I had the tank outside that. 

Just to confirm. Are we talking 16x16x16 area around the tank or the actual chunk?

Will report back tonight! Thanks bdew.

**Comment by bdew** [comment]
Actual chunk. But for rendering purposes it's a 16 high cube so 16x16x16, and no the whole 16x256x16 column.

As in, if the controller is say at 123,75,456 - then the cube starts at 112,64,448. 

Hope that makes sense :P

**Comment by Utildayael** [comment]
Yup that makes sense. Explains maybe why I couldn't repro in SP too. In SP I had a similar setup but my HP pipe ran about 30 units from the multi blocks so the tank was definitely far enough away. 

Btw I love the pipes! It's insane to watch it fill max size Mek dynamic tank from a infinite water block in about 1 sec. It hits so hard on SP that my game freezes for about a minute. Haha. Then again, that tank holds 96,000 buckets of fluid so er ya. :)

Having filtered network of one pipe for all fluid transport is also insanely helpful as long as I remember to set the filter _before_ connecting storage. :D

Will test. Thanks :)

**Comment by Utildayael** [comment]
So what is considered a complex structure out of curiosity? I assumed, maybe incorrectly, you were referring to multiblocks structures.

I moved my tank way away from the multiblock evap towers and still have the issue but I think I at least have it narrowed down to one block after using your suggestion. If I have a tank indicator in there, it stutters like crazy, remove it? Works fine. While sad to not have the indicator, it beats not having the tank at all or worse, the stuttering. 

So what's near the new spot? Mekanism machines. Just single block ore processing stuff. Pipes. Conduits. No multiblocks at all. Lots of Chisel factory blocks make up the "not a machine" component of the area if that matters.

**Comment by bdew** [comment]
> So what is considered a complex structure out of curiosity?

I said "heavy/complicated model" not "complex structure" :P

What counts as it is really technical, can't really say without looking at the relevant code and/or analyzing whta's going on with a profiler. Usually things that have dynamic models changing depending on internal state are a good candidate, but not all of them cause problems.

At any rate, i'll hopefully put up an expreimental fix for this in the next few hours.

**Comment by bdew** [comment]
Please try this version: https://minecraft.curseforge.com/projects/pressure-pipes/files/2328048

**Comment by Utildayael** [comment]
Gotcha. Sorry for some reason I immediately went to multiblock. :)  

Will test tho wasn't able to repro in SP, just on server which... I'm not admin of.

**Comment by Utildayael** [comment]
Ack. I owed you updates on this. That fix sorted this out. Thanks! :)

**Comment by bdew** [comment]
Yay
