### ISSUE TITLE
[Minor] Removing Tank Filter Block Doesn't Remove Filter

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/pressure#75]
Minor one for ya. Removing the tank filter block doesn't remove the filter from the tank.

Repro:
1. Build tank
2. Add filter block
3. Configure filter with a liquid type, I used brine
4. Break the filter block
5. Check controller and filter still exists

Found this out by accident as I was changing my tank config and accidently broke the tank filter block. Panic set in but as I looked at the tank, saw the filter was still there so no issue.

May be by design but wanted to report it in case that isn't the case.

Cheers

**Comment by bdew** [comment]
This is by design, you can set/remove the filter from the GUI without the block. It's there mostly for visually showing it.
