### ISSUE TITLE
[Request] Super Fluid Tool

### ISSUE THREAD

**Issue by Utildayael** [bdew-minecraft/pressure#76]
Idea for a useful tool which has no useful name currently.

Tool that can be built by the player to use on any Pressure Pipe block to query the network to see what fluids and amounts are in all connected storages. This could be built into the Fluid Filter Config tool as an additional ability.

Would be handy for a "what do I have in my network" check much like various mods have tools to measure fluid in pipes, energy in lines, etc.

May be difficult to get the storage containers into a pretty format, especially with multiblocks and whatnot [but I could be wrong] ... but having at least something like:

Water - 1000mb
Lava - 5000mb
Brine - 500mb
SomeOtherFluid - 5000mb

.... would be handy. If it shows what is in each container tho, that's bonus. :)

Container - x,y,z - Liquid - Amount
Drum - 1,2,3 - Lava - 50,000mb

Cheers

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
