### ISSUE TITLE
Can't pipe from IE coke oven into Pressure Pipes tank

### ISSUE THREAD

**Issue by topher2010** [bdew-minecraft/pressure#77]
I can't seem to use Pressure Pipes to pump into the Pressure Pipes tank from the Immersive Engineering coke oven.  I can use the pressure pipes to pump from the coke oven into an Extra Utilities 2 drum just fine, but not into the multiblock tank.  I can manually put the creosote oil directly into the tank, however that isn't automatable.

Edit: Forgot to mention this was with 1.10.2 pressure pipes 1.3.1.14 and Immersive Engineering 0.10-42

**Comment by demethan** [comment]
I got it working on the same pack.. I think we can close this Topher.

**Comment by bdew** [comment]
So did you fix it? What was the problem out of curiosity?

**Comment by demethan** [comment]
I can't confirm what my co-player was doing but I had it working just fine on the same pack. 

Coke Oven>pump>pressure in> pipe>pressure out> Tank intake

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
