### ISSUE TITLE
Crash with Cells from TechReborn

### ISSUE THREAD

**Issue by Sphysics** [bdew-minecraft/pressure#78]
When inserting a cell from TechReborn (filled with any fluid) into the Tank Controller crashes client and corrupts the world.

Steps to replicate:
1. Open Tank Controller GUI
2. Insert Cell

Mod Versions:
bdlib-1.12.2.12-mc1.10.2.
pressure-1.3.1.14-mc1.10.2.
TechReborn-1.10.2-1.4.3.52-universal

[crash-2016-09-28_00.14.41-server.txt](https://github.com/bdew/pressure/files/496815/crash-2016-09-28_00.14.41-server.txt)

**Comment by bdew** [comment]
I can't get the new cells from TR to work at all (they don't show in NEI and trying to craft them crashes my game).

I added a workaround for the error. If you can get the cells to work - please test with this version: https://minecraft.curseforge.com/projects/pressure-pipes/files/2333054

**Comment by Sphysics** [comment]
The link that you sent me does not work

**Comment by bdew** [comment]
Hm, works for me. Must be curseforge having issues or something.

Try this one instead: https://jenkins.bdew.net/job/pressure-1.10.2/15/artifact/build/libs/pressure-1.3.1.15-mc1.10.2.jar

**Comment by Sphysics** [comment]
It no longer crashes with the newer version

**Comment by bdew** [comment]
Great, closing this then.
