### ISSUE TITLE
Bug with Tank Indicator Blocks

### ISSUE THREAD

**Issue by Sphysics** [bdew-minecraft/pressure#79]
If there is a block in the front of a Tank Indicator Block, the indicator block will not render properly as shown in the screenshots.

pressure-1.3.1.15-mc1.10.2

![2016-09-29_15 13 49](https://cloud.githubusercontent.com/assets/7604644/18957577/885a7866-8657-11e6-81f1-a53737a8d3bd.png)
![2016-09-29_15 13 57](https://cloud.githubusercontent.com/assets/7604644/18957562/759ece02-8657-11e6-859b-258256a1e4e8.png)
![2016-09-29_15 13 52](https://cloud.githubusercontent.com/assets/7604644/18957561/759a5f5c-8657-11e6-96b1-508accf7bca9.png)
![2016-09-29_15 13 55](https://cloud.githubusercontent.com/assets/7604644/18957560/7597faa0-8657-11e6-90f8-5f0afa831675.png)

**Comment by bdew** [comment]
Fixed in this build https://jenkins.bdew.net/job/pressure-1.10.2/16/artifact/build/libs/pressure-1.3.1.16-mc1.10.2.jar
