### ISSUE TITLE
Request - config ability to disable matter state changes 

### ISSUE THREAD

**Issue by utoc** [bdew-minecraft/pressure#80]
Good day 

We're preparing to add pressure pipes to our pack and noticed that pressure pipes will convert gasses (Mekanism) to liquid much like the rotary condenserator. Is there any way to prohibit pipes from allowing matter state (gas to liquid, liquid to gas)? 

Thanks so much!

**Comment by bdew** [comment]
You could disable the recipes for the relevant parts for now. I'll add an option to disable them completely.

Though IMHO the liquid/gas distinction in mekanism seems pretty stupid to me. Forge fluid mechanics cover both and some often-used fluids in tech mod packs are actually gases (e.g. steam). Seems to me like different interface for the sake a different interface.

**Comment by utoc** [comment]
If its too much trouble, don't worry with it.  Mekanism uses a machine (that consumes energy) for state changes so I was trying to keep it relevant.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
