### ISSUE TITLE
[suggestion] Void upgrade for tank or liquid void block.

### ISSUE THREAD

**Issue by demethan** [bdew-minecraft/pressure#82]
Hi,  a small suggestion.

With Extra Utils not implementing its Liquid Trash. I find it would be nice to have a void upgrade on a tank. 

when the  tank is full then void extra liquid. 

Thanks

Love the mod.

**Comment by bdew** [comment]
Place a [drain](https://bdew.net/pressure/fluid-drain/) and put any block in front of it. It will just void anything it can't place.
