### ISSUE TITLE
[Suggestion] Hiding canisters in JEI as well as NEI

### ISSUE THREAD

**Issue by utoc** [bdew-minecraft/pressure#83]
Good morning, We're currently enjoying PressurePipes in 1.10.2 and would like to request that the following line:

`B:"Add filled canisters to NEI"=false`

also effect JEI in the same manner if it isn't too much to ask. We're running PP 1.3.1.17, bdlib 1.12.2.16 with FML 2109.  Please let me know if I have neglected to include anything.

**Comment by bdew** [comment]
Should be fixed in next build, option was renamed to Add filled canisters to JEI since NEI isn't really a thing anymore.
