### ISSUE TITLE
Fluid output not connecting to mods pipes.

### ISSUE THREAD

**Issue by demethan** [bdew-minecraft/pressure#84]
I have a hard time getting fluids out of a thank with the mods I have available.

Immersive engineering seems to connect but no fluid seem to travle.
Extra Utilities 2: the tank doesn't detect it as a valid fluid pipe
Integrated Tunnels: the tank doesn't detect it as a valid fluid pipe

The only way I get fluid out is if I use a (pressure fluid output >pressure pipe>pressure out>drum>node)

This is on 1.10.2 , Forge 2121 with your latest build.

pack: https://www.atlauncher.com/pack/BreakfastSpecial

**Comment by bdew** [comment]
IT and EU parts don't implement anything i can detect them by. If you really want to use them - put a Tank Access Port - it doesn't try to do anything smart and just allows anything to input from/output to the tank.

Not sure what's going on with IE. I can't get it to work either.

If you want a sane pipe system i highly recommend EnderIO which works correctly with everything.
