### ISSUE TITLE
Server crash if pump rotated with Immersive Engineering hammer.

### ISSUE THREAD

**Issue by demethan** [bdew-minecraft/pressure#85]
I was trying to rotate the pump in the direction I wanted. That kicked me and crash the server. Then ther server would crash every time I would login.  I had to turn on "delete erroring entity" in the forge.cfg to get back in.

I didn't try to reproduce the problem. 

Here is the crashlog.

http://pastebin.com/WR4myEkV

Forge 2121. 

pack https://www.atlauncher.com/pack/BreakfastSpecial

**Comment by bdew** [comment]
Can't reproduce this.

I see a bunch of other mods in the traceback, so i guess one of them does something weird. What was the exact setup around the pump when it happened?

**Comment by demethan** [comment]
We continued having random crashes and there is a Silent Gem patch that seems to have fixe the probleme. I can't reproduce the probleme either. If I manage to do it again. I'll take better notes.
