### ISSUE TITLE
Issues with forestry capsules. 1.10.2

### ISSUE THREAD

**Issue by Sp3rw3r** [bdew-minecraft/pressure#87]
I am sending lava refractory capsules to a tank interface. It fills both item slots. I think the second item slot should only accept empty fluid containers? Anyway it clogs up the system since there is no more room for the emptied capsules.

If there is space for the emptied refractory capsules I see the stack count go up to 65 sometimes. A minor detail I guess.

Lastly most machines destroy the wax and refractory capsules from forestry after use. If that makes things easier...

**Comment by bdew** [comment]
> I am sending lava refractory capsules to a tank interface. It fills both item slots. I think the second item slot should only accept empty fluid containers? 

Hmm, the second slot should not accept any items inserted externally. Both empty and full containers should go into the first slot then get filled/emptied and moved to the second.

I've tried and wasn't able to reproduce this. What are you using to move items? And are you sure it's not just your system bouncing the emptied containers back into the input and them getting re-filled?

> If there is space for the emptied refractory capsules I see the stack count go up to 65 sometimes.

Now that's really weird, i don't even see how that would be possible from the code

> Lastly most machines destroy the wax and refractory capsules from forestry after use. If that makes things easier...

I think it's a bug with how i do the draining... I'll see if i can fix it.

**Comment by bdew** [comment]
> > Lastly most machines destroy the wax and refractory capsules from forestry after use. If that makes things easier...
> 
> I think it's a bug with how i do the draining... I'll see if i can fix it.

Should be fixed in next build.

Not sure if the rest would still be relevant with that fix, but if you can figure out what exactly was going on there and how i might reproduce this i'll look into that.

**Comment by Sp3rw3r** [comment]
I'll test it again and post setup and other info.

**Comment by Sp3rw3r** [comment]
[1 too many](http://imgur.com/a/jsqNQ)
Not that it bothers me, but might be related to 
[lava in wrong slot](http://imgur.com/a/Z7Jvd)

In the most simple setup I was not able to reproduce,
But here it went wrong again:
[inserting lava capsules and withdraw lava same time](http://imgur.com/a/Nmjjz)

It is probably some rare edge case that has to do with speed too.
I could not reproduce with vanilla hoppers, so I cannot reproduce without other mods.

So far tested with enderio item conduit pipe, actually addition ESD and extra utilities transfer node/pipes.

**Comment by Sp3rw3r** [comment]
[Not funny](http://imgur.com/a/P2oN8)
Other fluid containers seem effected too.

**Comment by bdew** [comment]
Is that on 1.3.1.18 or 19?

**Comment by Sp3rw3r** [comment]
18 . I try the new one now.

**Comment by Sp3rw3r** [comment]
1.3.1.19
The capsules are getting destroyed. Other problem persist. It looks like the tank gets confused when adding fluid with a fluid canister and withdrawing fluid with a fluid valve at the same time.

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
