### ISSUE TITLE
Pressurized Gas Input/Output blocks for use with Mekanism 9.x not craftable

### ISSUE THREAD

**Issue by Silke-Smoothe** [bdew-minecraft/pressure#88]
MC 1.10.2
Mekanism 9.2.0
Pressure Pipes 1.3.1.18
bdlib 1.12.2.17
JEI 1.10.2-3.13.3.375

The Pressurized Gas Input/Output blocks from Pressure Pipes are not craftable. JEI shows the blocks, but has no recipe for them. Once cheated in via Creative or Cheat Mode, the blocks work as intended, moving gas into/out of tanks, pipes, machines, etc. I originally commented on closed issue  #71, but then realized that this may be a new issue to track.

I began with 140+ mods and guessed that one of the mods must have been removing/overwriting the recipe. So created a new instance with only the above listed mods. Same issue. Tried crafting the items with the recipes listed on the github page using both a vanilla crafting table and a Tinker's crafting station. No result.

Then I tried adding the recipes using CraftTweaker. Still no result.

Again, went with a new instance of just the above mods, however, while loading the truncated instance, I noticed an odd error flash by on the terminal window:

```
[12:48:26]` [Client thread/ERROR]: Error while processing RsRecipeShaped(List(IAI, I_I, IHI),StackBlock(pressure,GasInput,32767),1): Block name 'pressure:GasInput' resolved to Air. This probably means that it isn't registered.
[12:48:26] [Client thread/ERROR]: Error while processing RsRecipeShaped(List(IHI, I_I, IAI),StackBlock(pressure,GasOutput,32767),1): Block name 'pressure:GasOutput' resolved to Air. This probably means that it isn't `registered.
```

Minecraft loaded, so there was no crash report, but I can include a copy of the log if needed. On the Github page, it states that these input/output blocks require Mekanism 8.x to load. My guess is that since Mekanism 9.x is not Mekanism 8.x, Pressure Pipes is not registering these mod specific blocks and therefore making them uncraftable, although they are still showing up in JEI, and can be cheated in.

**Comment by bdew** [comment]
If it wasn't registering the blocks - you wouldn't see them in JEI :)

The problem was a small typo in the recipes, should be fixed in next build.

**Comment by Silke-Smoothe** [comment]
Excellent! I apologize for my lack of understanding code. Thank you for the rapid response and resolution! You do amazing work and it's very much appreciated. For future reference, was there any other information I could have provided to better assist you? Or was it too much information and therefore convoluted the issue? Again, thank you for your time and effort!

**Comment by bdew** [comment]
It's fine. In this case the errors from the log were enough to figure whats wrong, but in general having more information is always better :)
