### ISSUE TITLE
Unable to insert buckets into Multiblock tank

### ISSUE THREAD

**Issue by Darkere** [bdew-minecraft/pressure#89]
Buckets do not go into the Multiblock tank. Trying to insert a canister via shift clicking deletes it.
Version 1.11 -1.3.1.1

**Comment by bdew** [comment]
Partially fixed in bdlib 1.13.0.7

**Comment by bdew** [comment]
Should be fixed in Pressure Pipes 1.3.1.2 and BDLib 1.13.0.7
