### ISSUE TITLE
Updating Screen Events 

### ISSUE THREAD

**Issue by misterfixit** [bdew-minecraft/pressure#9]
Pressure pipes seems to be trying to render a liquid in a canister that is missing from the fluid registry, and is reproducible across many clients 
http://puu.sh/beVva/09bfba2d9d.txt

**Comment by bdew** [comment]
Someone has reported the exact same crash (BevoTechPack/BevoTechPack#270) and it was a corrupt install. I really don't see how it can happen unless something is seriously broken.

If it doesn't disappear after a reinstall, please post a full log from forge.

**Comment by bdew** [comment]
Actually on another look through forge code i can see how it happens. It's still something broken with one of the fluids but i can at least add a workaround and more specific warning that will name the fluid.

I've also opened a bug report in forge about the usefulness of that error: MinecraftForge/MinecraftForge#1374

**Comment by bdew** [comment]
Please try [this build](http://jenkins.bdew.net/job/pressure-1.7.10/lastSuccessfulBuild/artifact/build/libs/pressure-mc1710-0.9.2.16.jar) and post your log with that. It will hopefully not crash but the buggy fluid will cause problems elsewhere.

**Comment by misterfixit** [comment]
that link doesn't exist apparently or I cannot access it I get an error not found page

**Comment by bdew** [comment]
Huh, jenkins being weird i guess, try this - http://jenkins.bdew.net/job/pressure-1.7.10/16/artifact/build/libs/pressure-mc1710-0.9.2.16.jar

**Comment by misterfixit** [comment]
That version seems to have fixed the problem

**Comment by bdew** [comment]
As i said, it's just a workaround, you probably still have a broken fluid that will crash your game any time any mod makes a FluidStack from it.

Look for "Fluid <something> is not registered correctly" in your log or post it here.
