### ISSUE TITLE
Pressure Pipes drop stats from RCL liquid?

### ISSUE THREAD

**Issue by McJty** [bdew-minecraft/pressure#91]
I have seen people comment about this but apparently your pipes drop stats from the RCL liquid that my mod has. What is special about this liquid is that it keeps stats in the FluidStack (NBT data). It seems that your mod (while transfering that liquid) doesn't preserve that?

**Comment by bdew** [comment]
I don't intentionally drop the nbt tag anywhere (that i remember), but there might be bugs. I don't think i've seen any fluid with NBT data before...

I'll look into it later today.

**Comment by bdew** [comment]
There were a few places where i was making new fluidstacks (without copying the NBT tag) when distributing fluids, Should be fixed now.

**Comment by McJty** [comment]
Thanks!
