### ISSUE TITLE
Bdlibd crashes on server only

### ISSUE THREAD

**Issue by redmage17** [bdew-minecraft/pressure#92]
[crash-2017-01-14_15.18.46-server.txt](https://github.com/bdew/pressure/files/706199/crash-2017-01-14_15.18.46-server.txt)

**Comment by redmage17** [comment]
Well it seems it's Gendustry causing the crash was working previously, and rolled back to the last stable release 32 and still crashes

**Comment by bdew** [comment]
> Caused by: java.lang.ClassNotFoundException: scala.util.parsing.combinator.JavaTokenParsers

Your setup is borked. There should be a library named scala-parser-combinators_2.11-1.0.1.jar somewhere in your server setup, installed by forge or whatever you used to install. It's either missing or corrupt.
