### ISSUE TITLE
Server Crash (Not sure how)

### ISSUE THREAD

**Issue by broeredaan** [bdew-minecraft/pressure#98]
My server has been havaing crashses lately and it seems to come from your mod.
Here is the crashlog I get: https://pastebin.com/MSs0VDbP

Sadly I am not that great at reading crashlogs perhaps you know a fix / can fix in next version ^^

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
