### ISSUE TITLE
Sluice wiki page is wrong

### ISSUE THREAD

**Issue by AaronSzaboo** [bdew-minecraft/pressure#99]
The sluice's URL is https://bdew.net/sluice/
Going by the rest of the wiki pages, it should be https://bdew.net/pressure/sluice/

**Comment by bdew** [comment]
I'm closing this issue as part of a spring cleaning of my issue trackers from old stuff.

If you believe it's a bug that is still relevant in Minecraft 1.12 - Feel free to reopen it.
